### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터 빠르게 계산 해야함
- 행렬 데이터 matrix 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성
    - 선형대수학을 빠르게 연산
        - 스칼라, 벡터, 매트릭스

In [1]:
import numpy as np

In [2]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만으로 값을 구성할 수 있음

In [3]:
arrayy = np.array([1,2,3])
type(arrayy), arrayy

(numpy.ndarray, array([1, 2, 3]))

In [6]:
arrayy2 = np.array(
    [[1,2,3],
     [4,5,6]],)
arrayy2, arrayy2.ndim, arrayy2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [13]:
# 행렬의 모양(shape) 변경하기
arrayy2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [14]:
# 행렬 데이터의 선택 : offset index : masking

In [17]:
arrayy2[1][::-1], arrayy2[1][2], arrayy2[1,2]

(array([6, 5, 4]), 6, 6)

In [19]:
# 데이터 수정

In [22]:
arrayy2[1][2] = 10

In [23]:
arrayy2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [24]:
# 브로드캐스팅
arrayy2[0] = 9

In [25]:
arrayy2

array([[ 9,  9,  9],
       [ 4,  5, 10]])

In [27]:
# 조건으로 선택
idx = arrayy2 > 7

In [28]:
idx

array([[ True,  True,  True],
       [False, False,  True]])

In [29]:
arrayy2[idx]

array([ 9,  9,  9, 10])

In [30]:
arrayy2[idx] = 100
arrayy2

array([[100, 100, 100],
       [  4,   5, 100]])

In [31]:
# 행렬 데이터의 생성 2

In [33]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
data.dtype

dtype('float64')

In [35]:
data2 = data.astype("int")
data2.dtype

dtype('int32')

In [37]:
data = np.ones((2,3,2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [38]:
# arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [42]:
np.arange(5,10), np.arange(5,10,2)

(array([5, 6, 7, 8, 9]), array([5, 7, 9]))

In [2]:
A = np.array(
    [[1,10,20,30],
     [0,2,0,0],
     [0,40,3,50],
     [0,60,0,1]]
)
np.linalg.det(A)

6.0

In [13]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()
 
x = np.array([-0.1,0.1,0.2])
 
y = softmax(x)
y

array([0.28001309, 0.34200877, 0.37797814])

In [15]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

a = np.array([0.2,0.1,-0.1])

softmax(a)

array([0.37797814, 0.34200877, 0.28001309])

0.9900000000000001