### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1 : ndarray, np.array(iterable)
- 행렬의 생성 2 : ones, zeros
- 행렬 데이터 선택 : array[x,y,z]
- 행렬 데이터 수정
    - 행렬 데이터 선택
    - =, > (값(scalar, vector, matrix))
    - broadcasting 개념
- arrange : list에서 사용하는 range : 결과가 ndarray 타입

### quiz 
- 100 ~ 130까지 랜덤한 숫자를 가지는 8X8행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 랜덤한 행렬 데이터
```
datas = np.random.randint(100, 130, (8,8))
```
- 데이터 타입이 정수 -> 문자열 : ndarray.astype()


In [2]:
import numpy as np

In [7]:
datas = np.random.randint(100, 130, (8,8))
datas

array([[116, 122, 108, 103, 116, 111, 105, 119],
       [109, 114, 103, 100, 102, 109, 102, 117],
       [121, 128, 126, 116, 106, 110, 100, 105],
       [113, 116, 124, 111, 100, 127, 111, 116],
       [102, 102, 111, 129, 125, 121, 119, 126],
       [126, 109, 100, 125, 107, 101, 123, 118],
       [108, 110, 112, 108, 103, 114, 125, 105],
       [113, 112, 103, 129, 128, 120, 126, 115]])

In [10]:
data1 = np.array([1,2,3])
data2 = [True, False, True]
data1[data2] # 마스킹 : 셀렉팅 가능

array([1, 3])

In [17]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T,F matrix 생성
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [19]:
# 데이터 타입 str으로 변환
datas.dtype

dtype('int32')

In [20]:
result = datas.astype("str")
result

array([['116', '122', '108', '103', '116', '111', '105', '119'],
       ['109', '114', '103', '100', '102', '109', '102', '117'],
       ['121', '128', '126', '116', '106', '110', '100', '105'],
       ['113', '116', '124', '111', '100', '127', '111', '116'],
       ['102', '102', '111', '129', '125', '121', '119', '126'],
       ['126', '109', '100', '125', '107', '101', '123', '118'],
       ['108', '110', '112', '108', '103', '114', '125', '105'],
       ['113', '112', '103', '129', '128', '120', '126', '115']],
      dtype='<U11')

In [ ]:
# T,F matrix 이용하여 특정 조건의 데이터 선택 후 브로드캐스팅하게 값을 대입

In [22]:
result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fbz"

In [23]:
result

array([['116', '122', 'fiz', '103', '116', 'fiz', 'fbz', '119'],
       ['109', 'fiz', '103', 'buz', 'fiz', '109', 'fiz', 'fiz'],
       ['121', '128', 'fiz', '116', '106', 'buz', 'buz', 'fbz'],
       ['113', '116', '124', 'fiz', 'buz', '127', 'fiz', '116'],
       ['fiz', 'fiz', 'fiz', 'fiz', 'buz', '121', '119', 'fiz'],
       ['fiz', '109', 'buz', 'buz', '107', '101', 'fiz', '118'],
       ['fiz', 'buz', '112', 'fiz', '103', 'fiz', 'buz', 'fbz'],
       ['113', '112', '103', 'fiz', '128', 'fbz', 'fiz', 'buz']],
      dtype='<U11')

### Quiz
- 1~20까지 랜덤한 숫자를 가지는 5*5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수
```
np.min(ndarray), np.max(ndarray)
```

In [27]:
datas = np.random.randint(1,20,(5,5))
datas

array([[11, 17, 14,  1,  7],
       [ 2, 16,  8, 12, 13],
       [ 4,  8,  1,  2, 15],
       [17, 11,  8, 17,  7],
       [18,  3, 14,  8,  5]])

In [28]:
min_num, max_num = np.min(datas), np.max(datas)
min_num, max_num

(1, 18)

In [29]:
idx_min = datas == min_num
idx_max = datas == max_num

In [30]:
result = datas.astype("str")

In [31]:
result[idx_min] = "MIN"
result[idx_max] = "MAX"

In [32]:
result

array([['11', '17', '14', 'MIN', '7'],
       ['2', '16', '8', '12', '13'],
       ['4', '8', 'MIN', '2', '15'],
       ['17', '11', '8', '17', '7'],
       ['MAX', '3', '14', '8', '5']], dtype='<U11')

### 1. linspace, logspace 함수
- linspace : 설정한 범위에서 선형적으로 분할한 위치의 값을 출력
- logspace : 설정한 범위에서 로그로 분할한 위치의 값을 출력

In [2]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [3]:
# logspace
# log10(x1) = 2
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [4]:
# 30세에 연봉이 $100000 일 때, 60세 연봉이 $1000000 일 때
# 연봉이 선형으로 증가, 지수함수로 증가하는 두 경우에서의 40세, 50세 연봉을 출력

In [5]:
age_30 = 100000
age_60 = 1000000

In [6]:
np.linspace(age_30, age_60, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [8]:
np.logspace(np.log10(age_30), np.log10(age_60), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값을 설정값
- rand : 균등분포로 난수를 발생
- randn : 정규분포로 난수를 발생
- randint : 균등분포로 정수값을 발생
- suffle : 행렬 데이터를 섞어줌
- choice : 특정 확률로 데이터를 선택

In [10]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [11]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [5]:
# shuffle
r = np.random.randint(1, 10, (3,4))
r

array([[3, 7, 5, 2],
       [9, 4, 6, 9],
       [7, 1, 7, 5]])

In [6]:
np.random.shuffle(r)
r # 원소 다 바꾸고 싶으면 reshape으로 1차원 만들어 shuffle 해서 다시 reshape

array([[7, 1, 7, 5],
       [3, 7, 5, 2],
       [9, 4, 6, 9]])

In [8]:
# choice
np.random.choice(5,10,p=[0.1,0,0.4,0.2,0.3]) #0-4, 10개, 확률

array([2, 4, 2, 2, 4, 2, 3, 3, 4, 4])

In [10]:
# unique
np.unique(r, return_counts = True) # 유일한 값 뽑아줌, return_counts = True 나온 횟수 출력

(array([1, 2, 3, 4, 5, 6, 7, 9]), array([1, 1, 1, 1, 2, 1, 3, 2], dtype=int64))

### 3. 행렬 데이터의 결합
- concatenate

In [11]:
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(3,2))
na3 = np.random.randint(10, size=(3,3))

In [14]:
# 세로 결합
np.concatenate((na1, na3))

array([[6, 0, 2],
       [1, 8, 6],
       [9, 7, 9],
       [2, 4, 3],
       [2, 2, 6]])

In [15]:
# 가로 결합
np.concatenate((na2, na3), axis=1) # axis = 0 : 세로, 1 : 가로

array([[3, 5, 9, 7, 9],
       [2, 9, 2, 4, 3],
       [7, 0, 2, 2, 6]])

In [20]:
# c_, r_
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [22]:
# split, var, std, mean, ... 찾아서 해보기